###
GET http://localhost:3000/

###
GET http://localhost:3000/ciclo/listar/123/456

###
POST http://localhost:3000/ciclo/cadastrar
Content-Type: application/json

{
    "data" : "2021/04/08"
}